name: Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.13.1


      # Build from the subdirectory
      - name: Install dependencies (svelte-app)
        run: |
          cd app/svelte-app
          npm install

     
      - name: Build project (svelte-app)
        run: |
          cd app/svelte-app
          npm run build


      - name: Deploy (svelte-app)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/svelte-app/build # Adjust this path if necessary for the subdirectory output
