name: Deploy Astro App to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy-astro:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.13.1

      - name: Install dependencies for Astro
        run: |
          cd ./svelte-app
          npm install

      - name: Build Astro app
        run: |
          cd ./svelte-app
          npm run build

      - name: Deploy Astro app
        run: |
          cd ./svelte-app
          npm run deploy
